namespace Moq.AutoMock.Generator.Example.TUnit;

[ConstructorTests(TargetType = typeof(Controller))]
public partial class ControllerTests
{
    partial void AutoMockerTestSetup(Moq.AutoMock.AutoMocker mocker, string testName)
    {
        mocker.Use<string>("");
    }

    // TUnit uses source generators as well. Because source generators cannot see code generated by other generators, we must manually include these.
    // TUnit requires dynamic test injection in a class with a public parameterless constructor.
    // With a public method, called whatever you like, with a single parameter of DynamicTestBuilderContext, and the [DynamicTestBuilder] attribute.
    // https://tunit.dev/docs/experimental/dynamic-tests
    [DynamicTestBuilder]
    public static void BuildTests(DynamicTestBuilderContext context)
        => AddAutoMockerConstuctorTests(context);
}
