namespace Moq.AutoMock.Generator.Example.TUnit;



[ConstructorTests(TargetType = typeof(ControllerWithSomeNullableParameters), Behavior = TestGenerationBehavior.IgnoreNullableParameters)]
public partial class ControllerNullableParametersTests
{
    partial void AutoMockerTestSetup(Moq.AutoMock.AutoMocker mocker, string testName)
    {
        mocker.Use<string>("");
        mocker.Use<int?>(42);
        mocker.Use<int>(24);
    }

    // TUnit uses source generators as well. Because source generators cannot see code generated by other generators, we must manually include these.
    // TUnit requires dynamic test injection in a class with a public parameterless constructor.
    // With a public method, called whatever you like, with a single parameter of DynamicTestBuilderContext, and the [DynamicTestBuilder] attribute.
    // https://tunit.dev/docs/experimental/dynamic-tests
    [DynamicTestBuilder]
    public static void BuildTests(DynamicTestBuilderContext context)
        => AddAutoMockerConstuctorTests(context);
}
