using Microsoft.CodeAnalysis.Text;
using System.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;

using VerifyCS = Moq.AutoMocker.Generators.Tests.CSharpSourceGeneratorVerifier<Moq.AutoMocker.Generators.ApplicationInsightsExtensionSourceGenerator>;
using Microsoft.CodeAnalysis.Testing;

namespace Moq.AutoMocker.Generators.Tests;

[TestClass]
public class ApplicationInsightsGeneratorTests
{
    private const string ExpectedApplicationInsightsV3GeneratedFile = """
        #nullable enable
        // Generated by Moq.AutoMocker.Generators.ApplicationInsightsExtensionSourceGenerator.
        // Licensed under the MIT License. See LICENSE in the project root for license information.
        namespace Moq.AutoMock
        {
            using System;
            using System.Collections.Generic;
            using System.Diagnostics;
            using Microsoft.ApplicationInsights;
            using Microsoft.ApplicationInsights.Extensibility;
            using OpenTelemetry;
            using OpenTelemetry.Logs;
            using OpenTelemetry.Metrics;
            using OpenTelemetry.Trace;

            /// <summary>
            /// This class provides extension methods for interacting with Application Insights in an <see cref="AutoMocker"/> instance.
            /// </summary>
            static partial class AutoMockerApplicationInsightsExtensions
            {
                /// <summary>
                /// This method sets up <see cref="AutoMocker"/> with Application Insights 3.x services using OpenTelemetry in-memory exporters,
                /// ensuring TelemetryClient is properly configured and doesn't make real API calls.
                /// This allows telemetry tracking calls to be verified in tests.
                /// </summary>
                /// <param name="mocker">The <see cref="AutoMocker"/> instance.</param>
                /// <returns>The same <see cref="AutoMocker"/> instance passed as parameter, allowing chained calls.</returns>
                public static AutoMocker WithApplicationInsights(this AutoMocker mocker)
                {
                    if (mocker == null)
                    {
                        throw new ArgumentNullException(nameof(mocker));
                    }

                    var collector = new TelemetryCollector();

                    var telemetryConfiguration = new TelemetryConfiguration
                    {
                        SamplingRatio = 1.0f,
                        ConnectionString = "InstrumentationKey=00000000-0000-0000-0000-000000000000"
                    };

                    telemetryConfiguration.ConfigureOpenTelemetryBuilder(b => b
                        .WithLogging(l => l.AddInMemoryExporter(collector.LogRecords))
                        .WithMetrics(m => m.AddInMemoryExporter(collector.Metrics))
                        .WithTracing(t => t.AddInMemoryExporter(collector.Activities)));

                    var telemetryClient = new TelemetryClient(telemetryConfiguration);

                    mocker.Use(collector);
                    mocker.Use(telemetryConfiguration);
                    mocker.Use(telemetryClient);

                    return mocker;
                }

                /// <summary>
                /// Gets the collection of log records that have been captured through the OpenTelemetry in-memory exporter.
                /// This method retrieves log records from the in-memory exporter configured by <see cref="WithApplicationInsights"/>.
                /// </summary>
                /// <param name="mocker">The <see cref="AutoMocker"/> instance.</param>
                /// <returns>A list of log records that have been captured.</returns>
                /// <exception cref="ArgumentNullException">Thrown when <paramref name="mocker"/> is null.</exception>
                /// <exception cref="InvalidOperationException">Thrown when Application Insights has not been configured using <see cref="WithApplicationInsights"/>.</exception>
                public static IList<LogRecord> GetApplicationInsightsLogRecords(this AutoMocker mocker)
                {
                    return GetCollector(mocker).LogRecords;
                }

                /// <summary>
                /// Gets the collection of metrics that have been captured through the OpenTelemetry in-memory exporter.
                /// This method retrieves metrics from the in-memory exporter configured by <see cref="WithApplicationInsights"/>.
                /// </summary>
                /// <param name="mocker">The <see cref="AutoMocker"/> instance.</param>
                /// <returns>A list of metrics that have been captured.</returns>
                /// <exception cref="ArgumentNullException">Thrown when <paramref name="mocker"/> is null.</exception>
                /// <exception cref="InvalidOperationException">Thrown when Application Insights has not been configured using <see cref="WithApplicationInsights"/>.</exception>
                public static IList<OpenTelemetry.Metrics.Metric> GetApplicationInsightsMetrics(this AutoMocker mocker)
                {
                    return GetCollector(mocker).Metrics;
                }

                /// <summary>
                /// Gets the collection of activities (traces) that have been captured through the OpenTelemetry in-memory exporter.
                /// This method retrieves activities from the in-memory exporter configured by <see cref="WithApplicationInsights"/>.
                /// </summary>
                /// <param name="mocker">The <see cref="AutoMocker"/> instance.</param>
                /// <returns>A list of activities that have been captured.</returns>
                /// <exception cref="ArgumentNullException">Thrown when <paramref name="mocker"/> is null.</exception>
                /// <exception cref="InvalidOperationException">Thrown when Application Insights has not been configured using <see cref="WithApplicationInsights"/>.</exception>
                public static IList<Activity> GetApplicationInsightsActivities(this AutoMocker mocker)
                {
                    return GetCollector(mocker).Activities;
                }

                private static TelemetryCollector GetCollector(AutoMocker mocker)
                {
                    if (mocker == null)
                    {
                        throw new ArgumentNullException(nameof(mocker));
                    }

                    var collector = mocker.Get<TelemetryCollector>();
                    if (collector == null)
                    {
                        throw new InvalidOperationException("Application Insights has not been configured. Call WithApplicationInsights() first.");
                    }

                    return collector;
                }

                /// <summary>
                /// Collects telemetry items captured by the OpenTelemetry in-memory exporters for verification in tests.
                /// </summary>
                private sealed class TelemetryCollector
                {
                    public List<LogRecord> LogRecords { get; } = new List<LogRecord>();
                    public List<OpenTelemetry.Metrics.Metric> Metrics { get; } = new List<OpenTelemetry.Metrics.Metric>();
                    public List<Activity> Activities { get; } = new List<Activity>();
                }
            }
        }
        """;

    private const string ExpectedApplicationInsightsV3ObsoleteGeneratedFile = """
        #nullable enable
        // Generated by Moq.AutoMocker.Generators.ApplicationInsightsExtensionSourceGenerator.
        // Licensed under the MIT License. See LICENSE in the project root for license information.
        namespace Moq.AutoMock
        {
            using System;

            /// <summary>
            /// This class provides extension methods for interacting with Application Insights in an <see cref="AutoMocker"/> instance.
            /// </summary>
            static partial class AutoMockerApplicationInsightsExtensions
            {
                /// <summary>
                /// This method sets up <see cref="AutoMocker"/> with Application Insights services.
                /// To use this method with Application Insights 3.x, you must add a reference to the OpenTelemetry.Exporter.InMemory NuGet package.
                /// </summary>
                /// <param name="mocker">The <see cref="AutoMocker"/> instance.</param>
                /// <returns>The same <see cref="AutoMocker"/> instance passed as parameter, allowing chained calls.</returns>
                [Obsolete("To use WithApplicationInsights with Application Insights 3.x, add a reference to the OpenTelemetry.Exporter.InMemory NuGet package.")]
                public static AutoMocker WithApplicationInsights(this AutoMocker mocker)
                {
                    throw new InvalidOperationException("To use WithApplicationInsights with Application Insights 3.x, add a reference to the OpenTelemetry.Exporter.InMemory NuGet package.");
                }
            }
        }
        """;

    [TestMethod]
    public async Task WhenApplicationInsightsAssemblyIsNotReferenced_NoGenerationOccurs()
    {
        await new VerifyCS.Test
        {
            TestCode = "",
            ReferenceApplicationInsights = false
        }.RunAsync(TestContext.CancellationToken);
    }

    [TestMethod]
    public async Task WhenApplicationInsights3xIsReferencedWithoutInMemoryExporter_ObsoleteExtensionMethodIsGenerated()
    {
        await new VerifyCS.Test
        {
            CompilerDiagnostics = CompilerDiagnostics.None,
            ReferenceApplicationInsights = true,
            ReferenceOpenTelemetryInMemoryExporter = false,
            TestCode = "",
            TestState =
            {
                GeneratedSources =
                {
                    GetSourceFile(ExpectedApplicationInsightsV3ObsoleteGeneratedFile, "AutoMockerApplicationInsightsExtensions.g.cs")
                }
            }
        }.RunAsync(TestContext.CancellationToken);
    }

    [TestMethod]
    public async Task WhenApplicationInsights3xIsReferencedWithInMemoryExporter_WorkingExtensionMethodIsGenerated()
    {
        await new VerifyCS.Test
        {
            CompilerDiagnostics = CompilerDiagnostics.None,
            ReferenceApplicationInsights = true,
            ReferenceOpenTelemetryInMemoryExporter = true,
            TestCode = "",
            TestState =
            {
                GeneratedSources =
                {
                    GetSourceFile(ExpectedApplicationInsightsV3GeneratedFile, "AutoMockerApplicationInsightsExtensions.g.cs")
                }
            }
        }.RunAsync(TestContext.CancellationToken);
    }

    [TestMethod]
    public async Task WhenGeneratorIsDisabled_NoGenerationOccurs()
    {
        var test = new VerifyCS.Test
        {
            ReferenceApplicationInsights = true,
            TestCode = ""
        };
        test.SetGlobalOption("build_property.EnableMoqAutoMockerApplicationInsightsGenerator", "false");
        await test.RunAsync(TestContext.CancellationToken);
    }

    [TestMethod]
    public async Task WhenGeneratorIsExplicitlyEnabled_ExtensionMethodIsGenerated()
    {
        var test = new VerifyCS.Test
        {
            CompilerDiagnostics = CompilerDiagnostics.None,
            ReferenceApplicationInsights = true,
            ReferenceOpenTelemetryInMemoryExporter = true,
            TestCode = "",
            TestState =
            {
                GeneratedSources =
                {
                    GetSourceFile(ExpectedApplicationInsightsV3GeneratedFile, "AutoMockerApplicationInsightsExtensions.g.cs")
                }
            }
        };
        test.SetGlobalOption("build_property.EnableMoqAutoMockerApplicationInsightsGenerator", "true");
        await test.RunAsync(TestContext.CancellationToken);
    }

    private static (string FileName, SourceText SourceText) GetSourceFile(string content, string fileName)
    {
        return (Path.Combine("Moq.AutoMocker.Generators", "Moq.AutoMocker.Generators.ApplicationInsightsExtensionSourceGenerator", fileName), SourceText.From(content, Encoding.UTF8));
    }

    public TestContext TestContext { get; set; }
}
