using Microsoft.CodeAnalysis.Text;
using System.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;

using VerifyCS = Moq.AutoMocker.Generators.Tests.CSharpSourceGeneratorVerifier<Moq.AutoMocker.Generators.ApplicationInsightsExtensionSourceGenerator>;
using Microsoft.CodeAnalysis.Testing;

namespace Moq.AutoMocker.Generators.Tests;

[TestClass]
public class ApplicationInsightsGeneratorTests
{
    private const string ExpectedApplicationInsightsGeneratedFile = """
        #nullable enable
        // Generated by Moq.AutoMocker.Generators.ApplicationInsightsExtensionSourceGenerator.
        // Licensed under the MIT License. See LICENSE in the project root for license information.
        namespace Moq.AutoMock
        {
            using System;
            using System.Collections.Generic;
            using Microsoft.ApplicationInsights;
            using Microsoft.ApplicationInsights.Channel;
            using Microsoft.ApplicationInsights.Extensibility;
            using Moq.AutoMock.Resolvers;

            /// <summary>
            /// This class provides extension methods for interacting with Application Insights in an <see cref="AutoMocker"/> instance.
            /// </summary>
            public static class AutoMockerApplicationInsightsExtensions
            {
                /// <summary>
                /// This method sets up <see cref="AutoMocker"/> with Application Insights services,
                /// ensuring TelemetryClient is properly mocked and doesn't make real API calls.
                /// This allows telemetry tracking calls to be verified in tests.
                /// </summary>
                /// <param name="mocker">The <see cref="AutoMocker"/> instance.</param>
                /// <returns>The same <see cref="AutoMocker"/> instance passed as parameter, allowing chained calls.</returns>
                public static AutoMocker WithApplicationInsights(this AutoMocker mocker)
                {
                    if (mocker == null)
                    {
                        throw new ArgumentNullException(nameof(mocker));
                    }

                    // Create a fake telemetry channel that doesn't send telemetry
                    var fakeTelemetryChannel = new FakeTelemetryChannel();
                    
                    // Create TelemetryConfiguration with the fake channel
                    var telemetryConfiguration = new TelemetryConfiguration
                    {
                        TelemetryChannel = fakeTelemetryChannel,
                        ConnectionString = "InstrumentationKey=00000000-0000-0000-0000-000000000000"
                    };

                    // Create TelemetryClient with the configuration
                    var telemetryClient = new TelemetryClient(telemetryConfiguration);

                    // Register the instances
                    mocker.Use<ITelemetryChannel>(fakeTelemetryChannel);
                    mocker.Use<FakeTelemetryChannel>(fakeTelemetryChannel);
                    mocker.Use(telemetryConfiguration);
                    mocker.Use(telemetryClient);

                    return mocker;
                }

                /// <summary>
                /// Gets the collection of telemetry items that have been sent through the Application Insights TelemetryClient.
                /// This method retrieves telemetry from the <see cref="FakeTelemetryChannel"/> that was configured by <see cref="WithApplicationInsights"/>.
                /// </summary>
                /// <param name="mocker">The <see cref="AutoMocker"/> instance.</param>
                /// <returns>A read-only list of telemetry items that have been sent.</returns>
                /// <exception cref="ArgumentNullException">Thrown when <paramref name="mocker"/> is null.</exception>
                /// <exception cref="InvalidOperationException">Thrown when Application Insights has not been configured using <see cref="WithApplicationInsights"/>.</exception>
                public static IReadOnlyList<ITelemetry> GetSentTelemetry(this AutoMocker mocker)
                {
                    if (mocker == null)
                    {
                        throw new ArgumentNullException(nameof(mocker));
                    }

                    var channel = mocker.Get<FakeTelemetryChannel>();
                    if (channel == null)
                    {
                        throw new InvalidOperationException("Application Insights has not been configured. Call WithApplicationInsights() first.");
                    }

                    return channel.SentItems;
                }

                /// <summary>
                /// Fake telemetry channel that collects telemetry items for verification in tests.
                /// </summary>
                public sealed class FakeTelemetryChannel : ITelemetryChannel
                {
                    private readonly List<ITelemetry> _sentItems = new List<ITelemetry>();

                    public bool? DeveloperMode { get; set; }
                    public string? EndpointAddress { get; set; }

                    /// <summary>
                    /// Gets the collection of telemetry items that have been sent.
                    /// </summary>
                    public IReadOnlyList<ITelemetry> SentItems => _sentItems.AsReadOnly();

                    public void Send(ITelemetry item)
                    {
                        if (item != null)
                        {
                            _sentItems.Add(item);
                        }
                    }

                    public void Flush()
                    {
                        // No-op for testing
                    }

                    public void Dispose()
                    {
                        // No-op for testing
                    }
                }
            }
        }
        """;

    [TestMethod]
    public async Task WhenApplicationInsightsAssemblyIsNotReferenced_NoGenerationOccurs()
    {
        await new VerifyCS.Test
        {
            TestCode = "",
            ReferenceApplicationInsights = false
        }.RunAsync();
    }

    [TestMethod]
    public async Task WhenApplicationInsightsAssemblyIsReferenced_ExtensionMethodIsGenerated()
    {
        await new VerifyCS.Test
        {
            CompilerDiagnostics = CompilerDiagnostics.None,
            ReferenceApplicationInsights = true,
            TestCode = "",
            TestState =
            {
                GeneratedSources =
                {
                    GetSourceFile(ExpectedApplicationInsightsGeneratedFile, "AutoMockerApplicationInsightsExtensions.g.cs")
                }
            }
        }.RunAsync();
    }

    [TestMethod]
    public async Task WhenGeneratorIsDisabled_NoGenerationOccurs()
    {
        var test = new VerifyCS.Test
        {
            ReferenceApplicationInsights = true,
            TestCode = ""
        };
        test.SetGlobalOption("build_property.EnableMoqAutoMockerApplicationInsightsGenerator", "false");
        await test.RunAsync();
    }

    [TestMethod]
    public async Task WhenGeneratorIsExplicitlyEnabled_ExtensionMethodIsGenerated()
    {
        var test = new VerifyCS.Test
        {
            CompilerDiagnostics = CompilerDiagnostics.None,
            ReferenceApplicationInsights = true,
            TestCode = "",
            TestState =
            {
                GeneratedSources =
                {
                    GetSourceFile(ExpectedApplicationInsightsGeneratedFile, "AutoMockerApplicationInsightsExtensions.g.cs")
                }
            }
        };
        test.SetGlobalOption("build_property.EnableMoqAutoMockerApplicationInsightsGenerator", "true");
        await test.RunAsync();
    }

    private static (string FileName, SourceText SourceText) GetSourceFile(string content, string fileName)
    {
        return (Path.Combine("Moq.AutoMocker.Generators", "Moq.AutoMocker.Generators.ApplicationInsightsExtensionSourceGenerator", fileName), SourceText.From(content, Encoding.UTF8));
    }
}
