using Microsoft.CodeAnalysis.Text;
using System.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;

using VerifyCS = Moq.AutoMocker.Generators.Tests.CSharpSourceGeneratorVerifier<Moq.AutoMocker.Generators.FakeTimeProviderExtensionSourceGenerator>;
using Microsoft.CodeAnalysis.Testing;

namespace Moq.AutoMocker.Generators.Tests;

[TestClass]
public class FakeTimeProviderGeneratorTests
{
    private const string ExpectedFakeTimeProviderGeneratedFile = """
        #nullable enable
        // Generated by Moq.AutoMocker.Generators.FakeTimeProviderExtensionSourceGenerator.
        // Licensed under the MIT License. See LICENSE in the project root for license information.
        namespace Moq.AutoMock
        {
            using System;
            using Microsoft.Extensions.Time.Testing;

            /// <summary>
            /// This class provides extension methods for interacting with <see cref="FakeTimeProvider"/> in an <see cref="AutoMocker"/> instance.
            /// </summary>
            static partial class AutoMockerFakeTimeProviderExtensions
            {
                /// <summary>
                /// This method sets up <see cref="AutoMocker"/> with a <see cref="FakeTimeProvider"/> from Microsoft.Extensions.Time.Testing,
                /// allowing time-dependent components to be tested in a deterministic way.
                /// </summary>
                /// <param name="mocker">The <see cref="AutoMocker"/> instance.</param>
                /// <returns>The same <see cref="AutoMocker"/> instance passed as parameter, allowing chained calls.</returns>
                public static AutoMocker WithFakeTimeProvider(this AutoMocker mocker)
                {
                    if (mocker == null)
                    {
                        throw new ArgumentNullException(nameof(mocker));
                    }

                    var timeProvider = new FakeTimeProvider();
                    mocker.Use<TimeProvider>(timeProvider);
                    mocker.Use(timeProvider);

                    return mocker;
                }
            }
        }
        """;

    [TestMethod]
    public async Task WhenTimeProviderAssemblyIsNotReferenced_NoGenerationOccurs()
    {
        await new VerifyCS.Test
        {
            TestCode = "",
            ReferenceFakeTimeProvider = false
        }.RunAsync(TestContext.CancellationToken);
    }

    [TestMethod]
    public async Task WhenTimeProviderAssemblyIsReferenced_ExtensionMethodIsGenerated()
    {
        await new VerifyCS.Test
        {
            CompilerDiagnostics = CompilerDiagnostics.None,
            ReferenceFakeTimeProvider = true,
            TestCode = "",
            TestState =
            {
                GeneratedSources =
                {
                    GetSourceFile(ExpectedFakeTimeProviderGeneratedFile, "AutoMockerFakeTimeProviderExtensions.g.cs")
                }
            }
        }.RunAsync(TestContext.CancellationToken);
    }

    [TestMethod]
    public async Task WhenGeneratorIsDisabled_NoGenerationOccurs()
    {
        var test = new VerifyCS.Test
        {
            ReferenceFakeTimeProvider = true,
            TestCode = ""
        };
        test.SetGlobalOption("build_property.EnableMoqAutoMockerFakeTimeProviderGenerator", "false");
        await test.RunAsync(TestContext.CancellationToken);
    }

    [TestMethod]
    public async Task WhenGeneratorIsExplicitlyEnabled_ExtensionMethodIsGenerated()
    {
        var test = new VerifyCS.Test
        {
            CompilerDiagnostics = CompilerDiagnostics.None,
            ReferenceFakeTimeProvider = true,
            TestCode = "",
            TestState =
            {
                GeneratedSources =
                {
                    GetSourceFile(ExpectedFakeTimeProviderGeneratedFile, "AutoMockerFakeTimeProviderExtensions.g.cs")
                }
            }
        };
        test.SetGlobalOption("build_property.EnableMoqAutoMockerFakeTimeProviderGenerator", "true");
        await test.RunAsync(TestContext.CancellationToken);
    }

    private static (string FileName, SourceText SourceText) GetSourceFile(string content, string fileName)
    {
        return (Path.Combine("Moq.AutoMocker.Generators", "Moq.AutoMocker.Generators.FakeTimeProviderExtensionSourceGenerator", fileName), SourceText.From(content, Encoding.UTF8, SourceHashAlgorithm.Sha256));
    }

    public TestContext TestContext { get; set; }
}
