using System.Text;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Text;
using VerifyCS = Moq.AutoMocker.Generators.Tests.CSharpSourceGeneratorVerifier<Moq.AutoMocker.Generators.MeterFactoryExtensionSourceGenerator>;

namespace Moq.AutoMocker.Generators.Tests;

[TestClass]
public class MeterFactoryGeneratorTests
{
    private const string ExpectedMeterFactoryGeneratedFile = """
        #nullable enable
        // Generated by Moq.AutoMocker.Generators.MeterFactoryExtensionSourceGenerator.
        // Licensed under the MIT License. See LICENSE in the project root for license information.
        namespace Moq.AutoMock
        {
            using System;
            using System.Collections.Generic;
            using System.Diagnostics.Metrics;
            using Moq.AutoMock.Resolvers;

            /// <summary>
            /// This class provides extension methods for interacting with <see cref="IMeterFactory"/> in an <see cref="AutoMocker"/> instance.
            /// </summary>
            static partial class AutoMockerMeterFactoryExtensions
            {
                /// <summary>
                /// This method sets up <see cref="AutoMocker"/> with a meter factory that creates real <see cref="Meter"/> instances,
                /// allowing metrics testing scenarios without requiring a full DI container.
                /// </summary>
                /// <param name="mocker">The <see cref="AutoMocker"/> instance.</param>
                /// <returns>The same <see cref="AutoMocker"/> instance passed as parameter, allowing chained calls.</returns>
                public static AutoMocker WithMeterFactory(this AutoMocker mocker)
                {
                    if (mocker == null)
                    {
                        throw new ArgumentNullException(nameof(mocker));
                    }
        
                    var resolver = new MeterFactoryResolver();
                    mocker.InsertResolverAfter<CacheResolver>(resolver);
        
                    return mocker;
                }

                private sealed class MeterFactoryResolver : IMockResolver
                {
                    private AutoMockerMeterFactory? _factory;

                    public void Resolve(MockResolutionContext context)
                    {
                        if (context.RequestType == typeof(IMeterFactory))
                        {
                            _factory ??= new AutoMockerMeterFactory();
                            context.Value = _factory;
                        }
                    }
                }

                private sealed class AutoMockerMeterFactory : IMeterFactory
                {
                    private readonly List<Meter> _meters = new();

                    public Meter Create(MeterOptions options)
                    {
                        var meter = new Meter(options);
                        _meters.Add(meter);
                        return meter;
                    }

                    public void Dispose()
                    {
                        foreach (var meter in _meters)
                        {
                            meter.Dispose();
                        }
                        _meters.Clear();
                    }
                }
            }
        }
        """;

    [TestMethod]
    public async Task WhenDiagnosticSourceAssemblyIsNotReferenced_NoGenerationOccurs()
    {
        await new VerifyCS.Test
        {
            TestCode = "",
            ReferenceDiagnosticSource = false
        }.RunAsync(TestContext.CancellationToken);
    }

    [TestMethod]
    public async Task WhenDiagnosticSourceAssemblyIsReferenced_ExtensionMethodIsGenerated()
    {
        await new VerifyCS.Test
        {
            CompilerDiagnostics = CompilerDiagnostics.None,
            ReferenceDiagnosticSource = true,
            TestCode = "",
            TestState =
            {
                GeneratedSources =
                {
                    GetSourceFile(ExpectedMeterFactoryGeneratedFile, "AutoMockerMeterFactoryExtensions.g.cs")
                }
            }
        }.RunAsync(TestContext.CancellationToken);
    }

    [TestMethod]
    public async Task WhenGeneratorIsDisabled_NoGenerationOccurs()
    {
        var test = new VerifyCS.Test
        {
            ReferenceDiagnosticSource = true,
            TestCode = ""
        };
        test.SetGlobalOption("build_property.EnableMoqAutoMockerMeterFactoryGenerator", "false");
        await test.RunAsync(TestContext.CancellationToken);
    }

    [TestMethod]
    public async Task WhenGeneratorIsExplicitlyEnabled_ExtensionMethodIsGenerated()
    {
        var test = new VerifyCS.Test
        {
            CompilerDiagnostics = CompilerDiagnostics.None,
            ReferenceDiagnosticSource = true,
            TestCode = "",
            TestState =
            {
                GeneratedSources =
                {
                    GetSourceFile(ExpectedMeterFactoryGeneratedFile, "AutoMockerMeterFactoryExtensions.g.cs")
                }
            }
        };
        test.SetGlobalOption("build_property.EnableMoqAutoMockerMeterFactoryGenerator", "true");
        await test.RunAsync(TestContext.CancellationToken);
    }

    private static (string FileName, SourceText SourceText) GetSourceFile(string content, string fileName)
    {
        return (Path.Combine("Moq.AutoMocker.Generators", "Moq.AutoMocker.Generators.MeterFactoryExtensionSourceGenerator", fileName), SourceText.From(content, Encoding.UTF8));
    }

    public TestContext TestContext { get; set; }
}
