using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Moq.AutoMocker.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class ApplicationInsightsExtensionSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Check if the generator is enabled via MSBuild property
        IncrementalValueProvider<bool> isEnabled = context.AnalyzerConfigOptionsProvider
            .Select(static (provider, _) => IsGeneratorEnabled(provider));

        // Check if Microsoft.ApplicationInsights is referenced and get major version
        IncrementalValueProvider<int?> appInsightsMajorVersion = context.CompilationProvider
            .Select(static (compilation, _) => GetApplicationInsightsMajorVersion(compilation.ReferencedAssemblyNames));

        // Check if OpenTelemetry.Exporter.InMemory is referenced
        IncrementalValueProvider<bool> hasInMemoryExporter = context.CompilationProvider
            .Select(static (compilation, _) => ReferencesOpenTelemetryInMemoryExporter(compilation.ReferencedAssemblyNames));

        // Combine all conditions
        IncrementalValueProvider<(int? MajorVersion, bool HasInMemoryExporter)> generationInfo = isEnabled
            .Combine(appInsightsMajorVersion)
            .Combine(hasInMemoryExporter)
            .Select(static (tuple, _) =>
            {
                bool enabled = tuple.Left.Left;
                int? majorVersion = tuple.Left.Right;
                bool hasExporter = tuple.Right;
                if (!enabled) return ((int?)null, false);
                return (majorVersion, hasExporter);
            });

        // Generate source based on conditions
        context.RegisterSourceOutput(generationInfo, static (context, info) =>
        {
            if (info.MajorVersion is null) return;

            if (info.MajorVersion <= 2)
            {
                context.AddSource("AutoMockerApplicationInsightsExtensions.g.cs", ApplicationInsightsExtensionContentV2);
            }
            else
            {
                if (info.HasInMemoryExporter)
                {
                    context.AddSource("AutoMockerApplicationInsightsExtensions.g.cs", ApplicationInsightsExtensionContentV3);
                }
                else
                {
                    context.AddSource("AutoMockerApplicationInsightsExtensions.g.cs", ApplicationInsightsExtensionContentV3Obsolete);
                }
            }
        });
    }

    private static bool IsGeneratorEnabled(AnalyzerConfigOptionsProvider provider)
    {
        if (provider.GlobalOptions.TryGetValue("build_property.EnableMoqAutoMockerApplicationInsightsGenerator", out var value))
        {
            return !string.Equals(value, "false", StringComparison.OrdinalIgnoreCase);
        }
        return true; // Enabled by default
    }

    private static int? GetApplicationInsightsMajorVersion(IEnumerable<AssemblyIdentity> assemblies)
    {
        foreach (AssemblyIdentity assembly in assemblies)
        {
            if (assembly.Name.Equals("Microsoft.ApplicationInsights", StringComparison.OrdinalIgnoreCase))
            {
                return assembly.Version.Major;
            }
        }
        return null;
    }

    private static bool ReferencesOpenTelemetryInMemoryExporter(IEnumerable<AssemblyIdentity> assemblies)
    {
        foreach (AssemblyIdentity assembly in assemblies)
        {
            if (assembly.Name.Equals("OpenTelemetry.Exporter.InMemory", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }
        return false;
    }

    private const string ApplicationInsightsExtensionContentV2 =
        """
        #nullable enable
        // Generated by Moq.AutoMocker.Generators.ApplicationInsightsExtensionSourceGenerator.
        // Licensed under the MIT License. See LICENSE in the project root for license information.
        namespace Moq.AutoMock
        {
            using System;
            using System.Collections.Generic;
            using Microsoft.ApplicationInsights;
            using Microsoft.ApplicationInsights.Channel;
            using Microsoft.ApplicationInsights.Extensibility;
            using Moq.AutoMock.Resolvers;

            /// <summary>
            /// This class provides extension methods for interacting with Application Insights in an <see cref="AutoMocker"/> instance.
            /// </summary>
            static partial class AutoMockerApplicationInsightsExtensions
            {
                /// <summary>
                /// This method sets up <see cref="AutoMocker"/> with Application Insights services,
                /// ensuring TelemetryClient is properly mocked and doesn't make real API calls.
                /// This allows telemetry tracking calls to be verified in tests.
                /// </summary>
                /// <param name="mocker">The <see cref="AutoMocker"/> instance.</param>
                /// <returns>The same <see cref="AutoMocker"/> instance passed as parameter, allowing chained calls.</returns>
                public static AutoMocker WithApplicationInsights(this AutoMocker mocker)
                {
                    if (mocker == null)
                    {
                        throw new ArgumentNullException(nameof(mocker));
                    }

                    // Create a fake telemetry channel that doesn't send telemetry
                    var fakeTelemetryChannel = new FakeTelemetryChannel();
                    
                    // Create TelemetryConfiguration with the fake channel
                    var telemetryConfiguration = new TelemetryConfiguration
                    {
                        TelemetryChannel = fakeTelemetryChannel,
                        ConnectionString = "InstrumentationKey=00000000-0000-0000-0000-000000000000"
                    };

                    // Create TelemetryClient with the configuration
                    var telemetryClient = new TelemetryClient(telemetryConfiguration);

                    // Register the instances
                    mocker.Use<ITelemetryChannel>(fakeTelemetryChannel);
                    mocker.Use<FakeTelemetryChannel>(fakeTelemetryChannel);
                    mocker.Use(telemetryConfiguration);
                    mocker.Use(telemetryClient);

                    return mocker;
                }

                /// <summary>
                /// Gets the collection of telemetry items that have been sent through the Application Insights TelemetryClient.
                /// This method retrieves telemetry from the <see cref="FakeTelemetryChannel"/> that was configured by <see cref="WithApplicationInsights"/>.
                /// </summary>
                /// <param name="mocker">The <see cref="AutoMocker"/> instance.</param>
                /// <returns>A read-only list of telemetry items that have been sent.</returns>
                /// <exception cref="ArgumentNullException">Thrown when <paramref name="mocker"/> is null.</exception>
                /// <exception cref="InvalidOperationException">Thrown when Application Insights has not been configured using <see cref="WithApplicationInsights"/>.</exception>
                public static IReadOnlyList<ITelemetry> GetSentTelemetry(this AutoMocker mocker)
                {
                    if (mocker == null)
                    {
                        throw new ArgumentNullException(nameof(mocker));
                    }

                    var channel = mocker.Get<FakeTelemetryChannel>();
                    if (channel == null)
                    {
                        throw new InvalidOperationException("Application Insights has not been configured. Call WithApplicationInsights() first.");
                    }

                    return channel.SentItems;
                }

                /// <summary>
                /// Fake telemetry channel that collects telemetry items for verification in tests.
                /// </summary>
                public sealed class FakeTelemetryChannel : ITelemetryChannel
                {
                    private readonly List<ITelemetry> _sentItems = new List<ITelemetry>();

                    public bool? DeveloperMode { get; set; }
                    public string? EndpointAddress { get; set; }

                    /// <summary>
                    /// Gets the collection of telemetry items that have been sent.
                    /// </summary>
                    public IReadOnlyList<ITelemetry> SentItems => _sentItems.AsReadOnly();

                    public void Send(ITelemetry item)
                    {
                        if (item != null)
                        {
                            _sentItems.Add(item);
                        }
                    }

                    public void Flush()
                    {
                        // No-op for testing
                    }

                    public void Dispose()
                    {
                        // No-op for testing
                    }
                }
            }
        }
        """;

    private const string ApplicationInsightsExtensionContentV3 =
        """
        #nullable enable
        // Generated by Moq.AutoMocker.Generators.ApplicationInsightsExtensionSourceGenerator.
        // Licensed under the MIT License. See LICENSE in the project root for license information.
        namespace Moq.AutoMock
        {
            using System;
            using System.Collections.Generic;
            using System.Diagnostics;
            using Microsoft.ApplicationInsights;
            using Microsoft.ApplicationInsights.Extensibility;
            using OpenTelemetry;
            using OpenTelemetry.Logs;
            using OpenTelemetry.Metrics;
            using OpenTelemetry.Trace;

            /// <summary>
            /// This class provides extension methods for interacting with Application Insights in an <see cref="AutoMocker"/> instance.
            /// </summary>
            static partial class AutoMockerApplicationInsightsExtensions
            {
                /// <summary>
                /// This method sets up <see cref="AutoMocker"/> with Application Insights 3.x services using OpenTelemetry in-memory exporters,
                /// ensuring TelemetryClient is properly configured and doesn't make real API calls.
                /// This allows telemetry tracking calls to be verified in tests.
                /// </summary>
                /// <param name="mocker">The <see cref="AutoMocker"/> instance.</param>
                /// <returns>The same <see cref="AutoMocker"/> instance passed as parameter, allowing chained calls.</returns>
                public static AutoMocker WithApplicationInsights(this AutoMocker mocker)
                {
                    if (mocker == null)
                    {
                        throw new ArgumentNullException(nameof(mocker));
                    }

                    var collector = new TelemetryCollector();

                    var telemetryConfiguration = new TelemetryConfiguration
                    {
                        SamplingRatio = 1.0f,
                        ConnectionString = "InstrumentationKey=00000000-0000-0000-0000-000000000000"
                    };

                    telemetryConfiguration.ConfigureOpenTelemetryBuilder(b => b
                        .WithLogging(l => l.AddInMemoryExporter(collector.LogRecords))
                        .WithMetrics(m => m.AddInMemoryExporter(collector.Metrics))
                        .WithTracing(t => t.AddInMemoryExporter(collector.Activities)));

                    var telemetryClient = new TelemetryClient(telemetryConfiguration);

                    mocker.Use(collector);
                    mocker.Use(telemetryConfiguration);
                    mocker.Use(telemetryClient);

                    return mocker;
                }

                /// <summary>
                /// Gets the collection of log records that have been captured through the OpenTelemetry in-memory exporter.
                /// This method retrieves log records from the in-memory exporter configured by <see cref="WithApplicationInsights"/>.
                /// </summary>
                /// <param name="mocker">The <see cref="AutoMocker"/> instance.</param>
                /// <returns>A list of log records that have been captured.</returns>
                /// <exception cref="ArgumentNullException">Thrown when <paramref name="mocker"/> is null.</exception>
                /// <exception cref="InvalidOperationException">Thrown when Application Insights has not been configured using <see cref="WithApplicationInsights"/>.</exception>
                public static IList<LogRecord> GetApplicationInsightsLogRecords(this AutoMocker mocker)
                {
                    return GetCollector(mocker).LogRecords;
                }

                /// <summary>
                /// Gets the collection of metrics that have been captured through the OpenTelemetry in-memory exporter.
                /// This method retrieves metrics from the in-memory exporter configured by <see cref="WithApplicationInsights"/>.
                /// </summary>
                /// <param name="mocker">The <see cref="AutoMocker"/> instance.</param>
                /// <returns>A list of metrics that have been captured.</returns>
                /// <exception cref="ArgumentNullException">Thrown when <paramref name="mocker"/> is null.</exception>
                /// <exception cref="InvalidOperationException">Thrown when Application Insights has not been configured using <see cref="WithApplicationInsights"/>.</exception>
                public static IList<OpenTelemetry.Metrics.Metric> GetApplicationInsightsMetrics(this AutoMocker mocker)
                {
                    return GetCollector(mocker).Metrics;
                }

                /// <summary>
                /// Gets the collection of activities (traces) that have been captured through the OpenTelemetry in-memory exporter.
                /// This method retrieves activities from the in-memory exporter configured by <see cref="WithApplicationInsights"/>.
                /// </summary>
                /// <param name="mocker">The <see cref="AutoMocker"/> instance.</param>
                /// <returns>A list of activities that have been captured.</returns>
                /// <exception cref="ArgumentNullException">Thrown when <paramref name="mocker"/> is null.</exception>
                /// <exception cref="InvalidOperationException">Thrown when Application Insights has not been configured using <see cref="WithApplicationInsights"/>.</exception>
                public static IList<Activity> GetApplicationInsightsActivities(this AutoMocker mocker)
                {
                    return GetCollector(mocker).Activities;
                }

                private static TelemetryCollector GetCollector(AutoMocker mocker)
                {
                    if (mocker == null)
                    {
                        throw new ArgumentNullException(nameof(mocker));
                    }

                    var collector = mocker.Get<TelemetryCollector>();
                    if (collector == null)
                    {
                        throw new InvalidOperationException("Application Insights has not been configured. Call WithApplicationInsights() first.");
                    }

                    return collector;
                }

                /// <summary>
                /// Collects telemetry items captured by the OpenTelemetry in-memory exporters for verification in tests.
                /// </summary>
                private sealed class TelemetryCollector
                {
                    public List<LogRecord> LogRecords { get; } = new List<LogRecord>();
                    public List<OpenTelemetry.Metrics.Metric> Metrics { get; } = new List<OpenTelemetry.Metrics.Metric>();
                    public List<Activity> Activities { get; } = new List<Activity>();
                }
            }
        }
        """;

    private const string ApplicationInsightsExtensionContentV3Obsolete =
        """
        #nullable enable
        // Generated by Moq.AutoMocker.Generators.ApplicationInsightsExtensionSourceGenerator.
        // Licensed under the MIT License. See LICENSE in the project root for license information.
        namespace Moq.AutoMock
        {
            using System;

            /// <summary>
            /// This class provides extension methods for interacting with Application Insights in an <see cref="AutoMocker"/> instance.
            /// </summary>
            static partial class AutoMockerApplicationInsightsExtensions
            {
                /// <summary>
                /// This method sets up <see cref="AutoMocker"/> with Application Insights services.
                /// To use this method with Application Insights 3.x, you must add a reference to the OpenTelemetry.Exporter.InMemory NuGet package.
                /// </summary>
                /// <param name="mocker">The <see cref="AutoMocker"/> instance.</param>
                /// <returns>The same <see cref="AutoMocker"/> instance passed as parameter, allowing chained calls.</returns>
                [Obsolete("To use WithApplicationInsights with Application Insights 3.x, add a reference to the OpenTelemetry.Exporter.InMemory NuGet package.")]
                public static AutoMocker WithApplicationInsights(this AutoMocker mocker)
                {
                    throw new InvalidOperationException("To use WithApplicationInsights with Application Insights 3.x, add a reference to the OpenTelemetry.Exporter.InMemory NuGet package.");
                }
            }
        }
        """;
}
