using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Moq.AutoMocker.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class FakeTimeProviderExtensionSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Check if the generator is enabled via MSBuild property
        IncrementalValueProvider<bool> isEnabled = context.AnalyzerConfigOptionsProvider
            .Select(static (provider, _) => IsGeneratorEnabled(provider));

        // Check if Microsoft.Extensions.TimeProvider.Testing is referenced
        IncrementalValueProvider<bool> referencesFakeTimeProvider = context.CompilationProvider
            .Select(static (compilation, _) => ReferencesFakeTimeProvider(compilation.ReferencedAssemblyNames));

        // Combine both conditions
        IncrementalValueProvider<bool> shouldGenerate = isEnabled
            .Combine(referencesFakeTimeProvider)
            .Select(static (tuple, _) => tuple.Left && tuple.Right);

        // Only generate source if enabled and Microsoft.Extensions.TimeProvider.Testing is referenced
        context.RegisterSourceOutput(shouldGenerate, static (context, shouldGenerate) =>
        {
            if (shouldGenerate)
            {
                context.AddSource("AutoMockerFakeTimeProviderExtensions.g.cs", FakeTimeProviderExtensionContent);
            }
        });
    }

    private static bool IsGeneratorEnabled(AnalyzerConfigOptionsProvider provider)
    {
        if (provider.GlobalOptions.TryGetValue("build_property.EnableMoqAutoMockerFakeTimeProviderGenerator", out var value))
        {
            return !string.Equals(value, "false", StringComparison.OrdinalIgnoreCase);
        }
        return true; // Enabled by default
    }

    private static bool ReferencesFakeTimeProvider(IEnumerable<AssemblyIdentity> assemblies)
    {
        foreach (AssemblyIdentity assembly in assemblies)
        {
            if (assembly.Name.Equals("Microsoft.Extensions.TimeProvider.Testing", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }
        return false;
    }

    private const string FakeTimeProviderExtensionContent =
        """
        #nullable enable
        // Generated by Moq.AutoMocker.Generators.FakeTimeProviderExtensionSourceGenerator.
        // Licensed under the MIT License. See LICENSE in the project root for license information.
        namespace Moq.AutoMock
        {
            using System;
            using Microsoft.Extensions.Time.Testing;

            /// <summary>
            /// This class provides extension methods for interacting with <see cref="FakeTimeProvider"/> in an <see cref="AutoMocker"/> instance.
            /// </summary>
            static partial class AutoMockerFakeTimeProviderExtensions
            {
                /// <summary>
                /// This method sets up <see cref="AutoMocker"/> with a <see cref="FakeTimeProvider"/> from Microsoft.Extensions.Time.Testing,
                /// allowing time-dependent components to be tested in a deterministic way.
                /// </summary>
                /// <param name="mocker">The <see cref="AutoMocker"/> instance.</param>
                /// <returns>The same <see cref="AutoMocker"/> instance passed as parameter, allowing chained calls.</returns>
                public static AutoMocker WithFakeTimeProvider(this AutoMocker mocker)
                {
                    if (mocker == null)
                    {
                        throw new ArgumentNullException(nameof(mocker));
                    }

                    var timeProvider = new FakeTimeProvider();
                    mocker.Use<TimeProvider>(timeProvider);
                    mocker.Use(timeProvider);

                    return mocker;
                }
            }
        }
        """;
}
