using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Moq.AutoMocker.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class FakeLoggingExtensionSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Check if the generator is enabled via MSBuild property
        IncrementalValueProvider<bool> isEnabled = context.AnalyzerConfigOptionsProvider
            .Select(static (provider, _) => IsGeneratorEnabled(provider));

        // Check if Microsoft.Extensions.Diagnostics.Testing is referenced
        IncrementalValueProvider<bool> referencesFakeLogging = context.CompilationProvider
            .Select(static (compilation, _) => ReferencesFakeLogging(compilation.ReferencedAssemblyNames));

        // Combine both conditions
        IncrementalValueProvider<bool> shouldGenerate = isEnabled
            .Combine(referencesFakeLogging)
            .Select(static (tuple, _) => tuple.Left && tuple.Right);

        // Only generate source if enabled and Microsoft.Extensions.Diagnostics.Testing is referenced
        context.RegisterSourceOutput(shouldGenerate, static (context, shouldGenerate) =>
        {
            if (shouldGenerate)
            {
                context.AddSource("AutoMockerFakeLoggingExtensions.g.cs", FakeLoggingExtensionContent);
            }
        });
    }

    private static bool IsGeneratorEnabled(AnalyzerConfigOptionsProvider provider)
    {
        if (provider.GlobalOptions.TryGetValue("build_property.EnableMoqAutoMockerFakeLoggingGenerator", out var value))
        {
            return !string.Equals(value, "false", StringComparison.OrdinalIgnoreCase);
        }
        return true; // Enabled by default
    }

    private static bool ReferencesFakeLogging(IEnumerable<AssemblyIdentity> assemblies)
    {
        foreach (AssemblyIdentity assembly in assemblies)
        {
            if (assembly.Name.Equals("Microsoft.Extensions.Diagnostics.Testing", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }
        return false;
    }

    private const string FakeLoggingExtensionContent =
        """
        #nullable enable
        // Generated by Moq.AutoMocker.Generators.FakeLoggingExtensionSourceGenerator.
        // Licensed under the MIT License. See LICENSE in the project root for license information.
        namespace Moq.AutoMock
        {
            using System;
            using Microsoft.Extensions.Logging;
            using Microsoft.Extensions.Logging.Testing;
            using Moq.AutoMock.Resolvers;

            /// <summary>
            /// This class provides extension methods for interacting with fake logging in an <see cref="AutoMocker"/> instance.
            /// </summary>
            public static class AutoMockerFakeLoggingExtensions
            {
                /// <summary>
                /// This method sets up <see cref="AutoMocker"/> with fake logging services from Microsoft.Extensions.Logging.Testing,
                /// allowing logging interception and validation in testing scenarios.
                /// </summary>
                /// <param name="mocker">The <see cref="AutoMocker"/> instance.</param>
                /// <returns>The same <see cref="AutoMocker"/> instance passed as parameter, allowing chained calls.</returns>
                public static AutoMocker AddFakeLogging(this AutoMocker mocker)
                {
                    if (mocker == null)
                    {
                        throw new ArgumentNullException(nameof(mocker));
                    }

                    var provider = new FakeLoggerProvider();
                    var resolver = new FakeLoggerResolver(provider);
                    
                    // Find the CacheResolver and insert the FakeLoggerResolver after it
                    int cacheResolverIndex = -1;
                    for (int i = 0; i < mocker.Resolvers.Count; i++)
                    {
                        if (mocker.Resolvers[i] is CacheResolver)
                        {
                            cacheResolverIndex = i;
                            break;
                        }
                    }

                    if (cacheResolverIndex >= 0)
                    {
                        mocker.Resolvers.Insert(cacheResolverIndex + 1, resolver);
                    }
                    else
                    {
                        mocker.Resolvers.Insert(0, resolver);
                    }

                    mocker.Use(provider);
                    
                    return mocker;
                }

                private sealed class FakeLoggerResolver : IMockResolver
                {
                    private readonly FakeLoggerProvider _provider;

                    public FakeLoggerResolver(FakeLoggerProvider provider)
                    {
                        _provider = provider ?? throw new ArgumentNullException(nameof(provider));
                    }

                    public void Resolve(MockResolutionContext context)
                    {
                        if (context.RequestType == typeof(ILoggerFactory))
                        {
                            var loggerFactory = LoggerFactory.Create(b =>
                            {
                                b.SetMinimumLevel(LogLevel.Trace);
                                b.AddProvider(_provider);
                            });
                            context.Value = loggerFactory;
                        }
                        else if (context.RequestType.IsGenericType &&
                                context.RequestType.GetGenericTypeDefinition() == typeof(ILogger<>))
                        {
                            // Create a generic FakeLogger<T> for the requested type
                            var genericType = context.RequestType.GetGenericArguments()[0];
                            var fakeType = typeof(FakeLogger<>).MakeGenericType(genericType);

                            context.Value = Activator.CreateInstance(fakeType, _provider.Collector);
                        }
                        else if (context.RequestType == typeof(ILogger))
                        {
                            context.Value = _provider.CreateLogger("TestLogger");
                        }
                    }
                }
            }
        }
        """;
}
