using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Moq.AutoMocker.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class MeterFactoryExtensionSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Check if the generator is enabled via MSBuild property
        IncrementalValueProvider<bool> isEnabled = context.AnalyzerConfigOptionsProvider
            .Select(static (provider, _) => IsGeneratorEnabled(provider));

        // Check if System.Diagnostics.DiagnosticSource is referenced with version >= 10
        IncrementalValueProvider<bool> referencesDiagnosticSource = context.CompilationProvider
            .Select(static (compilation, _) => ReferencesDiagnosticSource(compilation.ReferencedAssemblyNames));

        // Combine both conditions
        IncrementalValueProvider<bool> shouldGenerate = isEnabled
            .Combine(referencesDiagnosticSource)
            .Select(static (tuple, _) => tuple.Left && tuple.Right);

        // Only generate source if enabled and System.Diagnostics.DiagnosticSource >= 10 is referenced
        context.RegisterSourceOutput(shouldGenerate, static (context, shouldGenerate) =>
        {
            if (shouldGenerate)
            {
                context.AddSource("AutoMockerMeterFactoryExtensions.g.cs", MeterFactoryExtensionContent);
            }
        });
    }

    private static bool IsGeneratorEnabled(AnalyzerConfigOptionsProvider provider)
    {
        if (provider.GlobalOptions.TryGetValue("build_property.EnableMoqAutoMockerMeterFactoryGenerator", out var value))
        {
            return !string.Equals(value, "false", StringComparison.OrdinalIgnoreCase);
        }
        return true; // Enabled by default
    }

    private static bool ReferencesDiagnosticSource(IEnumerable<AssemblyIdentity> assemblies)
    {
        foreach (AssemblyIdentity assembly in assemblies)
        {
            if (assembly.Name.Equals("System.Diagnostics.DiagnosticSource", StringComparison.OrdinalIgnoreCase))
            {
                // IMeterFactory was introduced in version 10.0
                return assembly.Version.Major >= 10;
            }
        }
        return false;
    }

    private const string MeterFactoryExtensionContent =
        """
        #nullable enable
        // Generated by Moq.AutoMocker.Generators.MeterFactoryExtensionSourceGenerator.
        // Licensed under the MIT License. See LICENSE in the project root for license information.
        namespace Moq.AutoMock
        {
            using System;
            using System.Collections.Generic;
            using System.Diagnostics.Metrics;
            using Moq.AutoMock.Resolvers;

            /// <summary>
            /// This class provides extension methods for interacting with <see cref="IMeterFactory"/> in an <see cref="AutoMocker"/> instance.
            /// </summary>
            static partial class AutoMockerMeterFactoryExtensions
            {
                /// <summary>
                /// This method sets up <see cref="AutoMocker"/> with a meter factory that creates real <see cref="Meter"/> instances,
                /// allowing metrics testing scenarios without requiring a full DI container.
                /// </summary>
                /// <param name="mocker">The <see cref="AutoMocker"/> instance.</param>
                /// <returns>The same <see cref="AutoMocker"/> instance passed as parameter, allowing chained calls.</returns>
                public static AutoMocker WithMeterFactory(this AutoMocker mocker)
                {
                    if (mocker == null)
                    {
                        throw new ArgumentNullException(nameof(mocker));
                    }
        
                    var resolver = new MeterFactoryResolver();
                    mocker.InsertResolverAfter<CacheResolver>(resolver);
        
                    return mocker;
                }

                private sealed class MeterFactoryResolver : IMockResolver
                {
                    private AutoMockerMeterFactory? _factory;

                    public void Resolve(MockResolutionContext context)
                    {
                        if (context.RequestType == typeof(IMeterFactory))
                        {
                            _factory ??= new AutoMockerMeterFactory();
                            context.Value = _factory;
                        }
                    }
                }

                private sealed class AutoMockerMeterFactory : IMeterFactory
                {
                    private readonly List<Meter> _meters = new();

                    public Meter Create(MeterOptions options)
                    {
                        var meter = new Meter(options);
                        _meters.Add(meter);
                        return meter;
                    }

                    public void Dispose()
                    {
                        foreach (var meter in _meters)
                        {
                            meter.Dispose();
                        }
                        _meters.Clear();
                    }
                }
            }
        }
        """;
}
